### ISSUE TITLE
Problem with integration

### ISSUE THREAD

**Issue by ripolltata** [IDmedia/hass-nohassle_hdmi_matrix#3]
Hello Goodnight!
I open a new issues to get things right.
First of all, I apologize if something is not well expressed because I do not speak English and I am translating everything with google.
I had asked you before because the integration did not work well. I ended up solving it with a universal go. But now I would like to know the state of the array to show it on some buttons, so I went back to research and found that you had made an update. Great! I updated and started testing it. I was very happy to see the developer tools and now I did see the information in the attributes.
The bad news was that he only showed it to me the first time and never again.
now I'm the same as before ...
I'm going to send you some screenshots to see if they work for you
I am working with the home attendant core-2021.3.4
my matrix is ​​8ch 4K
I could also copy the har file to inspect it, but I can't find how to share it

![matrix_atributos](https://user-images.githubusercontent.com/77713471/123722039-e88c5080-d85d-11eb-973a-ead4aaa12d3d.png)

![Matrix01](https://user-images.githubusercontent.com/77713471/123722085-035ec500-d85e-11eb-9f92-fc9e5d0cb36a.png)
page1

![Matrix02](https://user-images.githubusercontent.com/77713471/123722128-12de0e00-d85e-11eb-89c0-5df6c02eff3e.png)
page2

As you asked me, I tried clearing the registers and restart HA, the error you mentioned I don't appreciate, I got this "You are using a custom integration nohassle_hdmi_matrix which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant "
After restarting I can see the source in the attributes, but it is seen only once and then never again.

Then I tried "http: // IP_OF_YOUR_MATRIX / cgi-bin / query" in the browser and it showed me this {"comhead": "getpage1", "InStatus": [1,1,1,1,1,0,0 , 1], "OutHdmiStatus": [0,0,0,0,0,0,0,0], "OutHdbtStatus": [0,1,1,1,1,0,1,0], "PowerStatus ": [1]," BeepStatus ": [0]," McuVersion ":" V1.19 "}

Also researching there, I got to try this "python3 -c" import requests; print (requests.get ('http://192.168.100.181/cgi-bin/query') .json () ['SwitchStatus']) "" in terminal and showed me this [1, 2, 8, 3, 2, 2, 1, 1]

Hope this all helps to be able to integrate the matrix. It's a good job you did and I think that being able to include more models will be better.

Thank you very very much

**Comment by ripolltata** [comment]
I managed to convert the har file that I had saved to .txt
It's a bit long, I hope it works. If I can do something else I will gladly do it.

[no-hassle.txt](https://github.com/IDmedia/hass-nohassle_hdmi_matrix/files/6730021/no-hassle.txt)

Thanks again

**Comment by IDmedia** [comment]
Thank you. :)
According to the .har file you sent it seems the Matrix only response correctly only after requesting `http://192.168.100.181/cgi-bin/submit?cmd=getpage2!` first. I've made a small modification to the integration. It now requests `cmd=getpage2!` before asking for the current state. Not sure if the integration needs to request this on every update or not, but let's start with that...

Could you please download [this file](https://github.com/IDmedia/hass-nohassle_hdmi_matrix/files/6732001/media_player.py.txt). Change the extention from .txt to .py and replace the file with the one in your `custom_components` directory. Then clear the logs and restart Home Assistant.

1) Make sure your `media_player` entities have the `Source` attribute and that it stays there
2) Try to change source and see if that works using the service-call in the readme

If this file works for you I'll update the code in Github and close the issue, if not I'll have to dig a bit deeper.

**Comment by ripolltata** [comment]
Hello good Morning!!!
I tested the file you sent me and it worked perfectly ... both to see the status of the sources and the change with set_zone

Thank you very very much

You're a genius 👍

**Comment by IDmedia** [comment]
Awsome, glad to hear that. I'll push the update to Github and close this issue. Updating thought HACS will just replace the file again.
