### ISSUE TITLE
Magic Numbers Depreciation

### ISSUE THREAD

**Issue by matthew-hz** [IDmedia/hass-nohassle_hdmi_matrix#4]
Feature depreciated in Home Assistant and will be removed in 2025.1.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1607
First occurred: 7:15:34 AM (9 occurrences)
Last logged: 7:16:38 AM

Entity media_player.bar_patio_tv_1_source (<class 'custom_components.nohassle_hdmi_matrix.media_player.HDMIMatrixZone'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.SELECT_SOURCE: 2048>, please report it to the author of the 'nohassle_hdmi_matrix' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity media_player.bar_patio_tv_2_source (<class 'custom_components.nohassle_hdmi_matrix.media_player.HDMIMatrixZone'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.SELECT_SOURCE: 2048>, please report it to the author of the 'nohassle_hdmi_matrix' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity media_player.island_bar_tv_1_source (<class 'custom_components.nohassle_hdmi_matrix.media_player.HDMIMatrixZone'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.SELECT_SOURCE: 2048>, please report it to the author of the 'nohassle_hdmi_matrix' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity media_player.bar_living_room_source (<class 'custom_components.nohassle_hdmi_matrix.media_player.HDMIMatrixZone'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.SELECT_SOURCE: 2048>, please report it to the author of the 'nohassle_hdmi_matrix' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by IDmedia** [comment]
Should be fixed now
